name: kisak-core22
base: core22
adopt-info: mesa
summary: kisak mesa libraries for core22 snaps
description: |
  A content snap containing updated mesa libraries and drivers for core 22
compression: lzo

grade: stable
confinement: strict

package-repositories:
  - type: apt
    ppa: kisak/kisak-mesa

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  multiarch:
    plugin: nil
    override-pull: |
      if dpkg-architecture --is amd64; then
        dpkg --add-architecture i386
        apt-get update
      fi

  mesa:
    after: [multiarch]
    plugin: nil
    override-pull:
      craftctl set version=`LANG=C apt-cache policy libgl1-mesa-dri | sed -rne 's/^\s+Candidate:\s+([^-~]*)[-~].+$/\1/p'`
    stage-packages:
      - libgl1-mesa-dri
      - va-driver-all
      - libegl1
      - libgles2
      - to amd64:
        - libgl1-mesa-dri:i386
        - va-driver-all:i386
        - libegl1:i386
        - libgles2:i386
    organize:
      'usr/lib/x86_64-linux-gnu/dri/*': egl/dri/
      'usr/lib/x86_64-linux-gnu/*.so*': egl/lib/
      'usr/lib/i386-linux-gnu/dri/*': egl/dri-i386/
      'usr/lib/i386-linux-gnu/*.so*': egl/lib-i386/
      'usr/share/glvnd': egl/glvnd/
      'usr/share/libdrm': egl/libdrm/
      'usr/share/drirc.d/': egl/drirc.d/
    prime:
      - egl/lib
      - egl/dri
      - egl/lib-i386
      - egl/dri-i386
      - egl/glvnd
      - egl/libdrm
      - egl/drirc.d

slots:
  graphics-core22:
    interface: content
    read: 'egl'
